contest/weekly-contest-154/problems/maxNumberOfBalloons/README.md, contest/weekly-contest-154/problems/maxNumberOfBalloons/maxNumberOfBalloons.go, contest/weekly-contest-154/problems/maxNumberOfBalloons/maxNumberOfBalloons_test.go
=> Weekly contest 154

valid-parentheses/README.md, valid-parentheses/validParentheses.go, valid-parentheses/validParentheses_test.go
考えうるダメなパターンを列挙し、全ての検査を抜けたらTrueとした。
空文字列の場合trueを返すようにした
考えつかず、solutionを見た。
See. https://leetcode.com/problems/valid-parentheses/discuss/132069/16-lines-Go-Solution
その翌日にそらで書き直し。
その前にHintを見て自己解決図るべきだった。
=> feat(valid-parentheses): first submit version

merge-two-sorted-lists/README.md, merge-two-sorted-lists/mergeTwoLists.go, merge-two-sorted-lists/mergeTwoLists_test.go
- L1, L2毎にloopでStackに積む
- 積んだstackをソート
- 大きい値から、ListNodeに入れていく
- 一番大きい値を入れる際、Nextはnil
- その後はNextにloop前の値をいれていく
=> feat(merge-two-sorted-lists)

.travis.yml, merge-two-sorted-lists/mergeTwoLists.go, merge-two-sorted-lists/mergeTwoLists_test.go
Discussを確認したところ、https://github.com/lupinthe14th/leetcode/pull/13 でやった内容は仕様を満たしていなかった。
https://leetcode.com/problems/merge-two-sorted-lists/discuss/167437/go-solution
=> fix(merge-two-sorted-lists)

ugly-number/README.md, ugly-number/isUgly.go, ugly-number/isUgly_test.go
- numを2で割れるか判定。
- 割れると判定されたら、実際に２で割った値でnumを更新
- 割れなくなったらループを抜ける
- numが1か判定
- 1ならば戻り値をtrueで返して終了
- これを３と５と続ける。
- 5が終わった後でnumが1でない場合は、戻り値をfalseで返して終了
- num が0 と1のパターンを追加
=> feat(ugly-number)

ugly-number/isUgly.go
https://leetcode.com/problems/ugly-number/discuss/318727/GO-solution-0ms
=> improve(ugly-number):

remove-duplicates-from-sorted-array/removeDuplicates_test.go
=> fix(remove-duplicates-from-sorted-array)

remove-element/removeElement.go, remove-element/removeElement_test.go
seen 26. Remove Duplicates from Sorted Array solution
=> feat(remove-element)

implement-strstr/README.md, implement-strstr/strStr.go, implement-strstr/strStr_test.go
- 与えられた文字列から初期判定処理
- 比較する文字列が空の場合、0を返す
- 比較対象文字列が空の場合と、比較する文字列が比較対象文字列より文字数が大きい場合は、一部となり得ないので-1を返す
- forループで文字列を検索。ループインデックスから比較対象文字列長で切り出した値が比較対象文字列と同じ場合、ループインデックを返す
- ループを全て回しても条件に合致しない場合、-1を返して終了
=> feat(implement-strstr)

problems/search-insert-position/README.md, problems/search-insert-position/searchInsert.go, problems/search-insert-position/searchInsert_test.go
=> feat(search-insert-position)

contest/biweekly-contest-10/problems/intersection-of-three-sorted-arrays/arraysIntersection.go, contest/biweekly-contest-10/problems/intersection-of-three-sorted-arrays/arraysIntersection_test.go
=> feat(intersection-of-three-sorted-arrays)

problems/maximum-subarray/maxSubArray.go, problems/maximum-subarray/maxSubArray_test.go
- https://leetcode.com/problems/maximum-subarray/discuss/20193/DP-solution-and-some-thoughts
- https://leetcode.com/problems/maximum-subarray/discuss/290007/Go-4-ms-100.00-easy-code
- https://leetcode.com/problems/maximum-subarray/discuss/309414/Go-Simple-DP-solution
=> feat(maximum-subarray): first submit version

contest/weekly-contest-160/problems/circular-permutation-in-binary-representation/circularPermutation.go, contest/weekly-contest-160/problems/circular-permutation-in-binary-representation/circularPermutation_test.go
- https://leetcode.com/problems/circular-permutation-in-binary-representation/discuss/414203/JavaC%2B%2BPython-4-line-Gray-Code
=> feat(circular-permutation-in-binary-representation): second commit version

contest/weekly-contest-160/problems/circular-permutation-in-binary-representation/circularPermutation.go
Runtime: 3656 ms -> 3452 ms
Memory: 9.7 MB -> 9.5 MB
=> improve: refactor code

contest/weekly-contest-162/problems/cells-with-odd-values-in-a-matrix/oddCells.go, contest/weekly-contest-162/problems/cells-with-odd-values-in-a-matrix/oddCells_test.go
=> feat(cells-with-odd-values-in-a-matrix): first submit version

contest/weekly-contest-162/problems/cells-with-odd-values-in-a-matrix/oddCells.go
- https://leetcode.com/problems/cells-with-odd-values-in-a-matrix/discuss/425187/C%2B%2B-brute-force
=> improve(cells-with-odd-values-in-a-matrix): refactor code

problems/house-robber/rob.go, problems/house-robber/rob_test.go
Give up!
https://leetcode.com/problems/house-robber/discuss/351833/Go-DP-solution
=> House robber

contest/biweekly-contest-13/problems/encode-number/encode.go, contest/biweekly-contest-13/problems/encode-number/encode_test.go
=> feat(encode-number): first submit version

problems/remove-duplicates-from-sorted-list/deleteDuplicates.go, problems/remove-duplicates-from-sorted-list/deleteDuplicates_test.go
=> feat(remove-duplicates-from-sorted-list): first submit version

problems/intersection-of-two-arrays/intersection.go, problems/intersection-of-two-arrays/intersection_test.go
=> feat(intersection-of-two-arrays): first submit version

problems/plus-one/plusOne.go, problems/plus-one/plusOne_test.go
=> feat(plus-one): first submit version

contest/weekly-contest-165/problems/find-winner-on-a-tic-tac-toe-game/tictactoe.go, contest/weekly-contest-165/problems/find-winner-on-a-tic-tac-toe-game/tictactoe_test.go
=> Find winner on a tic tac toe game

contest/weekly-contest-165/problems/count-square-submatrices-with-all-ones/countSquares.go, contest/weekly-contest-165/problems/count-square-submatrices-with-all-ones/countSquares_test.go
Refarence: https://leetcode.com/problems/count-square-submatrices-with-all-ones/discuss/441399/c-dp-solution-with-video-explenation-by-tushar-roy
=> feat(count-square-submatrices-with-all-ones): refarence version

contest/weekly-contest-166/problems/subtract-the-product-and-sum-of-digits-of-an-integer/subtractProductAndSum.go, contest/weekly-contest-166/problems/subtract-the-product-and-sum-of-digits-of-an-integer/subtractProductAndSum_test.go
=> feat(weekly-contest-166/problems/subtract-the-product-and-sum-of-digits-of-an-integer)

problems/climbing-stairs/climbStairs.go, problems/climbing-stairs/climbStairs_test.go
- [世界で闘うプログラミング力を鍛える本 \~コーディング面接189問とその解法\~](https://www.amazon.co.jp/dp/4839960100/ref=cm_sw_em_r_mt_dp_U_USo5Db4M1J5P3)
階段を上り終える、一番最後のステップは何段ですか？
n段目で上り終える時、一番最後のステップは2ステップ、1ステップのいずれかです。
n段目で最後まで到達するには何通りの方法があるでしょうか。それはまだわかりませんが、いくつかの部分問題に関連付けることができます。
n段目までのすべての経路について考えた場合、前のステップごとに経路を分けて組み立てることができます。
n段目に到達するのは、次のいずれかの方法です。
- (n-1)段目まで進み、1段上がる
- (n-2)段目まで進み、2段上がる
したがって、これらの経路の数を合計するだけで済みます。
基底状態、つまり階段の0段目にいる場合。その段までの経路は0でしょうか。あるいは1でしょうか。
どちらでも定義可能です。正しい答えはありません。
しかし、1と定義する方がはるかに簡単です。0と定義した場合、追加の基底状態が必要になります。
これからフィボナッチ数列のように実装できます。
ブルートフォースでも良いですが、このアルゴリズムの実行時間は指数関数的（2つの分岐を繰り返すためO(2^n)） になるのでメモ化を使って改良します。
メモ化で使うキャッシュはmap[int]int を使うとシンプルです。
ですが、n=46でオーバーフローするので、uintを使って実装し直したり、math/bigを使って実装し直すのも良いかと。
=> Climbing stairs

contest/weekly-contest-166/problems/find-the-smallest-divisor-given-a-threshold/smallestDivisor.go, contest/weekly-contest-166/problems/find-the-smallest-divisor-given-a-threshold/smallestDivisor_test.go
=> feat(weekly-contest-166/find-the-smallest-divisor-given-a-threshold)

problems/min-cost-climbing-stairs/minCostClimbingStairs.go, problems/min-cost-climbing-stairs/minCostClimbingStairs_test.go
I can't solve this problem.
seen solution.
=> feat(min-cost-climbing-stairs): solution version

problems/divisor-game/divisorGame.go, problems/divisor-game/divisorGame_test.go
- https://leetcode.com/problems/divisor-game/discuss/274566/just-return-N-2-0-(proof)
- https://leetcode.com/problems/divisor-game/discuss/274606/JavaC++Python-return-N-2-0
- https://leetcode.com/problems/divisor-game/discuss/324107/JAVA-How-I-think-using-DP
=> feat(divisor-game): I couldn't self-solve this problem.

contest/weekly-contest-166/problems/group-the-people-given-the-group-size-they-belong-to/groupThePeople.go, contest/weekly-contest-166/problems/group-the-people-given-the-group-size-they-belong-to/groupThePeople_test.go
https://leetcode.com/problems/group-the-people-given-the-group-size-they-belong-to/discuss/448744/Go-HashMap-with-Greedy
=> Weekly contest 166/group the people given the group size they belong to

contest/weekly-contest-166/problems/group-the-people-given-the-group-size-they-belong-to/groupThePeople.go
refactor code.
- add loop counter
=> weekly-contest-166/group-the-people-given-the-group-size-they-belong-to

problems/best-time-to-buy-and-sell-stock/maxProfit.go, problems/best-time-to-buy-and-sell-stock/maxProfit_test.go
Algorithm:  brute force solution
Algorithm: Dynamic Programming?
Algorithm|Time Submitted | Runtime | Memory
-- | -- | -- | --
Dynamic Programming|a few seconds ago |  4 ms | 3.1 MB
Brute Force|37 minutes ago | 268 ms | 3.1 MB
=> feat(best-time-to-buy-and-sell-stock):

problems/best-time-to-buy-and-sell-stock/maxProfit.go
See: https://leetcode.com/problems/best-time-to-buy-and-sell-stock/discuss/449566/Go-dp-solution
=> improve(best-time-to-buy-and-sell-stock): refactor code. update comment

contest/biweekly-contest-15/problems/element-appearing-more-than-25-in-sorted-array/findSpecialInteger.go, contest/biweekly-contest-15/problems/element-appearing-more-than-25-in-sorted-array/findSpecialInteger_test.go
=> feat(biweekly-contest-15/element-appearing-more-than-25-in-sorted-array

contest/weekly-contest-167/problems/convert-binary-number-in-a-linked-list-to-integer/getDecimalValue.go, contest/weekly-contest-167/problems/convert-binary-number-in-a-linked-list-to-integer/getDecimalValue_test.go
=> feat(weekly-contest-167/convert-binary-number-in-a-linked-list-to-integer

contest/weekly-contest-168/problems/find-numbers-with-even-number-of-digits/findNumbers.go, contest/weekly-contest-168/problems/find-numbers-with-even-number-of-digits/findNumbers_test.go
=> feat(weekly-contest-168/find-numbers-with-even-number-of-digits):

contest/weekly-contest-168/problems/divide-array-in-sets-of-k-consecutive-numbers/isPossibleDivide.go, contest/weekly-contest-168/problems/divide-array-in-sets-of-k-consecutive-numbers/isPossibleDivide_test.go
以下の場合は自明なので条件に合致する場合はreturnする。
- 配列長がkで割り切れない場合はFalseを返す。
- kが1ならtrueを返す。
上記自明以外は貪慾法で調べていく。
- numsはソートされていないのでソートする
- numsの値をキーとし、値はそのキーの個数となるハッシュマップを作成する。
- ソート済numsの最小値から最大値まで以下を繰り返す
- ハッシュマップにその値をキーとした値が0以上の場合、その値が未使用の最小値となる
- 最小値が決まったら、ハッシュマップからそのキーをデクリメントする
- 決まった最小値を使って、長さkの連続した数値のスライスを作成する。つまり、最小値をインクリメントした値がハッシュマップになければそこで条件に沿ったスライスは作成できないのでfalseを返します。
- 途中でfalseとなることなくループを終わらせることができたらtrueを返して終了します。
=> feat(weekly-contest-168/divide-array-in-sets-of-k-consecutive-numbers):

problems/continuous-subarray-sum/checkSubarraySum.go, problems/continuous-subarray-sum/checkSubarraySum_test.go
Approach 1: Algorithms: brute force. I can self-solve this problem.
=> feat(continuous-subarray-sum):

problems/combine-two-tables/exec.sql
- テーブルに別名つけると遅くなる（200ms程度）のでなるべく使わない
=> feat(combine-two-tables)

problems/second-highest-salary/exec.sql
accepted! on-sight!
- 副問い合わせで最大値を取得
- 取得した最大値を除外した最大値を取得する
Approach: Using IFNULL and LIMIT clause [Accepted]
=> feat(second-highest-salary)

problems/employees-earning-more-than-their-managers/exec.sql
SeeAlso: Approach I: Using WHERE clause [Accepted]
=> feat(employees-earning-more-than-their-managers): Seen solution

problems/range-sum-query-immutable/solution.go, problems/range-sum-query-immutable/solution_test.go
Accepted
Accepted
Time Submitted | Status | Runtime | Memory | Language
-- | -- | -- | -- | --
a few seconds ago | Accepted | 36 ms | 10.7 MB | golang
15 minutes ago | Accepted | 72 ms | 8.5 MB | golang
=> feat(range-sum-query-immutable): 

problems/exec.sql
Approach II: Using GROUP BY and HAVING condition
=> feat(duplicate-emails)

problems/customers-who-never-order/exec.sql
- Approach I: Using sub-query and NOT IN clause
- Approach II: Using Left join and is null clause
=> feat(customers-who-never-order): 

problems/delete-duplicate-emails/exec.sql
I coudn't self-solve this problem.
I seen Solution, approach: Using delete and where clause.
=> feat(delete-duplicate-emails):

problems/rising-temperature/exec.sql
I couldn't self-solve this problem.
I didn't understand the problem.
=> feat(rising-temperature):

contest/weekly-contest-169/problems/find-n-unique-integers-sum-up-to-zero/solution.go, contest/weekly-contest-169/problems/find-n-unique-integers-sum-up-to-zero/solution_test.go, contest/weekly-contest-169/problems/jump-game-iii/12, contest/weekly-contest-169/problems/jump-game-iii/solution.go, contest/weekly-contest-169/problems/jump-game-iii/solution_test.go
- Algorithms: simple
- Algorithms: DFS
=> Weekly contest 169

contest/biweekly-contest-16/problems/replace-elements-with-greatest-element-on-right-side/solution.go, contest/biweekly-contest-16/problems/replace-elements-with-greatest-element-on-right-side/solution_test.go, contest/biweekly-contest-16/problems/sum-of-mutated-array-closest-to-target/solution.go, contest/biweekly-contest-16/problems/sum-of-mutated-array-closest-to-target/solution_test.go
I could self-solve this problem
Accepted: On-sight
=> biweekly-contest-16

problems/big-countries/exec.sql
=> feat(big-countries):

contest/weekly-contest-170/decrypt-string-from-alphabet-to-integer-mapping/solution.go, contest/weekly-contest-170/decrypt-string-from-alphabet-to-integer-mapping/solution_test.go, contest/weekly-contest-170/xor-queries-of-a-subarray/solution.go, contest/weekly-contest-170/xor-queries-of-a-subarray/solution_test.go
- Decrypt String from Alphabet to Integer Mapping: Using number -> Alphabets mapping structure
- 文字列を前から一つずつ探索し、それぞれにマッピングしたアルファベットを結合して返す。
- 探索位置から2つ先の位置がスライス長を超えていた場合は1-9の数字とマッピングしたアルファベットを結合させる
- 超えていない場合は
- 探索位置から2つ先の位置に#があった場合は、探索位置から2つ先を合わせた文字列とマッピングしたアルファベットを結合させる
- そうでない場合は、1-9の数字とマッピングしたアルファベットを結合させる
- XOR Queries of a Subarray: Using Greedy? algorithms
- 回答用の配列を作成
- L=Rの場合はその配列番号の値を回答の配列に追加
- そうで無い場合は、
- 最初のxorを計算してxに代入
- 次回以降は前回のxorの結果とループ番号の次の配列番号のxorの値をxに代入
- ループが終わったら最終的なxの値を回答の配列に追加
- これらをクエリーの組み合わせすべて行った結果を返す
=> Weekly contest 170

problems/symmetric-tree/solution.go, problems/symmetric-tree/solution_test.go
I couldn't self solve this problem
- Algorithms: recursive, binary heap
=> feat(symmetric-tree)

contest/weekly-contest-170/minimum-insertion-steps-to-make-a-string-palindrome/solution.go, contest/weekly-contest-170/minimum-insertion-steps-to-make-a-string-palindrome/solution_test.go
- minimum-insertion-steps-to-make-a-string-palindrome
- Approach: len(s) - LCS:(Longest Common Subsequence)
@beet-aizu
=> feat(weekly-contest-170

contest/biweekly-contest-17/decompress-run-length-encoded-list/solution.go, contest/biweekly-contest-17/decompress-run-length-encoded-list/solution_test.go, contest/biweekly-contest-17/matrix-block-sum/solution.go, contest/biweekly-contest-17/matrix-block-sum/solution_test.go
- Decompress Run-Length Encoded List: It took time to understand the problem.
- Matrix Block Sum: Time over
=> Biweekly contest 17

problems/binary-tree-inorder-traversal/solution.go, problems/binary-tree-inorder-traversal/solution_test.go
例示されたテストケースをスライスから作り上げる方法がわからず、別のテストケースとしている。
=> feat(binary-tree-inorder-traversal):

contest/weekly-contest-172/maximum-69-number/solution.go, contest/weekly-contest-172/maximum-69-number/solution_test.go, contest/weekly-contest-172/print-words-vertically/solution.go, contest/weekly-contest-172/print-words-vertically/solution_test.go
- maximum-69-number: greedy approach. int -> string -> int. non clever.
- print-words-vertically: split -> max unit length -> space or string(rune) -> trim trailing spaces
=> Weekly contest 172

contest/weekly-contest-171/convert-integer-to-the-sum-of-two-no-zero-integers/solution.go, contest/weekly-contest-171/convert-integer-to-the-sum-of-two-no-zero-integers/solution_test.go, contest/weekly-contest-171/minimum-flips-to-make-a-or-b-equal-to-c/solution.go, contest/weekly-contest-171/minimum-flips-to-make-a-or-b-equal-to-c/solution_test.go
- convert-integer-to-the-sum-of-two-no-zero-integers: Self solve
- minimum-flips-to-make-a-or-b-equal-to-c: Couldn't self solve
=> Weekly contest 171

problems/number-complement/solution.go, problems/number-complement/solution_test.go
numの2進数桁数を求める。
log2(num) + 1
その桁分、1bitごとに調べる
- numの2進数i桁が1の場合 -> 0 ( ans &^= 1<< i)
- numの2進数i桁が0の場合 -> 1 ( ans |= 1<< i)
=> feat(number-complement)

contest/weekly-contest-173/filter-restaurants-by-vegan-friendly-price-and-distance/solution.go, contest/weekly-contest-173/filter-restaurants-by-vegan-friendly-price-and-distance/solution_test.go, contest/weekly-contest-173/remove-palindromic-subsequences/solution.go, contest/weekly-contest-173/remove-palindromic-subsequences/solution_test.go
- remove-palindromic-subsequences: See comment
- filter-restaurants-by-vegan-friendly-price-and-distance: starlight forward
=> Weekly contest 173

problems/longest-univalue-path/solution.go, problems/longest-univalue-path/solution_test.go
I couldn't self solve this problem. I don't think this problem is easy.
=> feat(longest-univalue-path): 

problems/path-sum-iii/solution.go, problems/path-sum-iii/solution_test.go
I couldn't self solve this problem
algorithms: 
- tree-traversal
- recursive
- preorder traversal
refacence:
- https://leetcode.com/problems/path-sum-iii/discuss/91960/Golang-recursive-DFS
- https://leetcode.com/problems/path-sum-iii/discuss/295843/C++-PreOrder-traversal-with-recusrion-:-20-ms
=> feat(path-sum-iii):

problems/binary-tree-postorder-traversal/solution.go, problems/binary-tree-postorder-traversal/solution_test.go
I couldn't self solve this problem.
Post-order traversal is to visit the root Finary. Then traverse the left subtree. first, traverse the right subtree.
recursive
```golang
func preorderTraversal(root *TreeNode) []int {
acc := make([]int, 0)
preorderRecursive(&acc, root)
return acc
}
func preorderRecursive(acc *[]int, root *TreeNode) {
if root == nil {
return
}
*acc = append(*acc, root.Val)
preorderRecursive(acc, root.Left)
preorderRecursive(acc, root.Right)
}
```
Iterative method with Stack
```golang
func preorderTraversal(root *TreeNode) []int {
ans := make([]int, 0)
if root == nil {
return ans 
}
stack := make([]*TreeNode, 0)
stack = append(stack, root)
for len(stack) != 0 {
visit := stack[len(stack)-1]
stack = stack[:len(stack)-1]
ans = append(ans, visit.Val)
if visit.Left != nil { …
```
=> feat(binary-tree-postorder-traversal):

contest/weekly-contest-174/reduce-array-size-to-the-half/solution.go, contest/weekly-contest-174/reduce-array-size-to-the-half/solution_test.go, contest/weekly-contest-174/the-k-weakest-rows-in-a-matrix/solution.go, contest/weekly-contest-174/the-k-weakest-rows-in-a-matrix/solution_test.go
- the-k-weakest-rows-in-a-matrix: idx & sum structure slice, sort.Slice
- reduce-array-size-to-the-half: approach: hashmap & arithmetic
=> weekly-contest-174

contest/biweekly-contest-19/angle-between-hands-of-a-clock/solution.go, contest/biweekly-contest-19/angle-between-hands-of-a-clock/solution_test.go, contest/biweekly-contest-19/number-of-steps-to-reduce-a-number-to-zero/solution.go, contest/biweekly-contest-19/number-of-steps-to-reduce-a-number-to-zero/solution_test.go, contest/biweekly-contest-19/number-of-sub-arrays-of-size-k-and-average-greater-than-or-equal-to-threshold/solution.go, contest/biweekly-contest-19/number-of-sub-arrays-of-size-k-and-average-greater-than-or-equal-to-threshold/solution_test.go
- number-of-steps-to-reduce-a-number-to-zero: greedy & arithmetic
- number-of-sub-arrays-of-size-k-and-average-greater-than-or-equal-to-threshold: greedy & arithmeti
- angle-between-hands-of-a-clock: arithmetic
=> biweekly-contest-19

contest/weekly-contest-175/check-if-n-and-its-double-exist/solution.go, contest/weekly-contest-175/check-if-n-and-its-double-exist/solution_test.go, contest/weekly-contest-175/minimum-number-of-steps-to-make-two-strings-anagram/solution.go, contest/weekly-contest-175/minimum-number-of-steps-to-make-two-strings-anagram/solution_test.go, contest/weekly-contest-175/tweet-counts-per-frequency/solution.go, contest/weekly-contest-175/tweet-counts-per-frequency/solution_test.go
- check-if-n-and-its-double-exist: greedy
- minimum-number-of-steps-to-make-two-strings-anagram: Using hashmap & arithmetic
=> Weekly contest 175

problems/maximum-depth-of-binary-tree/solution.go, problems/maximum-depth-of-binary-tree/solution_test.go
approach: recursion & top-down solution
=> maximum-depth-of-binary-tree

contest/weekly-contest-176/count-negative-numbers-in-a-sorted-matrix/solution.go, contest/weekly-contest-176/count-negative-numbers-in-a-sorted-matrix/solution_test.go, contest/weekly-contest-176/maximum-number-of-events-that-can-be-attended/solution.go, contest/weekly-contest-176/maximum-number-of-events-that-can-be-attended/solution_test.go, contest/weekly-contest-176/product-of-the-last-k-numbers/solution.go, contest/weekly-contest-176/product-of-the-last-k-numbers/solution_test.go
- count-negative-numbers-in-a-sorted-matrix: brute force
- product-of-the-last-k-numbers: arithmetic
- maximum-number-of-events-that-can-be-attended: Priority Queue
- https://leetcode.com/problems/maximum-number-of-events-that-can-be-attended/discuss/510263/JavaC++Python-Priority-Queue
- https://golang.org/pkg/container/heap/#example__intHeap
=> Weekly contest 176

contest/biweekly-contest-20/apply-discount-every-n-orders/solution.go, contest/biweekly-contest-20/apply-discount-every-n-orders/solution_test.go, contest/biweekly-contest-20/sort-integers-by-the-number-of-1-bits/[, contest/biweekly-contest-20/sort-integers-by-the-number-of-1-bits/solution.go, contest/biweekly-contest-20/sort-integers-by-the-number-of-1-bits/solution_test.go
- sort-integers-by-the-number-of-1-bits: matrix & sort
- apply-discount-every-n-orders: hashmap & arithmetic
=> Biweekly contest 20

contest/weekly-contest-177/closest-divisors/solution.go, contest/weekly-contest-177/closest-divisors/solution_test.go, contest/weekly-contest-177/number-of-days-between-two-dates/solution.go, contest/weekly-contest-177/number-of-days-between-two-dates/solution_test.go, contest/weekly-contest-177/validate-binary-tree-nodes/solution.go, contest/weekly-contest-177/validate-binary-tree-nodes/solution_test.go
- number-of-days-between-two-dates: time.Duration & arithmetic
=> weekly-contest-177

contest/weekly-contest-178/how-many-numbers-are-smaller-than-the-current-number/solution.go, contest/weekly-contest-178/how-many-numbers-are-smaller-than-the-current-number/solution_test.go, contest/weekly-contest-178/linked-list-in-binary-tree/solution.go, contest/weekly-contest-178/linked-list-in-binary-tree/solution_test.go, contest/weekly-contest-178/rank-teams-by-votes/solution.go, contest/weekly-contest-178/rank-teams-by-votes/solution_test.go
- how-many-numbers-are-smaller-than-the-current-number: brute force
- rank-teams-by-votes: Create the frequency array of i-th place votes for each team, then we can sort the frequency arrays.
- linked-list-in-binary-tree: seen discuss
=> weekly-contest-178

explore/other/card/30-day-leetcoding-challenge/528/week-1/happynumber/solution.go, explore/other/card/30-day-leetcoding-challenge/528/week-1/happynumber/solution_test.go
https://leetcode.com/explore/featured/card/30-day-leetcoding-challenge/528/week-1/3284/
=> approach: hash & arithmetic

explore/other/card/30-day-leetcoding-challenge/528/week-1/singlenumber/solution.go
If we take XOR of zero and some bit, it will return that bit.
e.g. a XOR 0 = a
If we take XOR of two same bits, it will return 0.
e.g. a XOR a = 0
a XOR b XOR a = (a XOR a) XOR b = 0 XOR b = b
So we can XOR all bits together to find the unique number.
=> single number:  approach: Bit Manipulation

explore/other/card/30-day-leetcoding-challenge/528/week-2/middleofthelinkedlist/solution.go
Intuition and Algorithm
When traversing the list with a pointer slow, make another pointer fast that traverses twice as fast. When fast reaches the and of the list, slow must be in the middle.
=> MiddleoftheLinkedList: Fast and Slow Pointer

explore/other/card/30-day-leetcoding-challenge/528/week-1/groupanagrams/solution_test.go
=> Group Anagrams: improve refactor test code

explore/other/card/30-day-leetcoding-challenge/528/week-1/groupanagrams/solution_test.go
Reverts lupinthe14th/leetcode#127
=> Revert "Group Anagrams: improve refactor test code"

explore/other/card/30-day-leetcoding-challenge/528/week-2/backspacestringcompare/solution.go, explore/other/card/30-day-leetcoding-challenge/528/week-2/backspacestringcompare/solution_test.go
直感
文字を書くとき、将来何回バックスペースキーを押すかによって、最終的な文字列の一部になるかどうかが決まります。
代わりに、文字列を逆に反復処理すると、何個のバックスペース文字があったかがわかり、結果に文字が含まれているかどうかがわかります。
アルゴリズム
文字列を逆に繰り返し処理します。バックスペース文字がある場合、次の非バックスペース文字はスキップされます。文字がスキップされなかった場合、それは最終的な答えの一部となります。
=> Backspace String Compare: Approach: Two Pointer

explore/other/card/30-day-leetcoding-challenge/528/week-2/diameterofbinarytree/solution.go, explore/other/card/30-day-leetcoding-challenge/528/week-2/diameterofbinarytree/solution_test.go
直感
どんなパスでも、あるノードから2本の矢印（方向が異なる）として書くことができ、矢印はあるノードを起点とし、子ノードまでしか下がらないパスです。
各子ノードに対する最大長の矢印 L, R を知っていれば、最良のパスは L + R + 1 ノードに接触します。
アルゴリズム
ノードの深さを通常の方法で計算してみましょう：max(depth of node.left, depth of node.right) + 1. そうしている間に，このノードを通るパスは，1 + (node.leftの深さ) + (node.rightの深さ)のノードを使用します．各ノードを検索して、いくつかのパスで使用されるノードの最大数を覚えておきましょう。望ましい長さは、この数から1を引いたものです。
=> Diameter of Binary Tree: Depth-First Search

contest/weekly-contest-184/queries-on-a-permutation-with-key/solution.go, contest/weekly-contest-184/queries-on-a-permutation-with-key/solution_test.go, contest/weekly-contest-184/string-matching-in-an-array/solution.go, contest/weekly-contest-184/string-matching-in-an-array/solution_test.go
- String Matching in an Array: using hashmap & check substring
- Queries on a Permutation With Key: using slice tricks
=> Weekly contest 184

explore/other/card/30-day-leetcoding-challenge/528/week-3/productofarrayexceptself/solution.go, explore/other/card/30-day-leetcoding-challenge/528/week-3/productofarrayexceptself/solution_test.go
- using division 
- without division and O(n)
=> Productof array except self

contest/weekly-contest-185/display-table-of-food-orders-in-a-restaurant/solution.go, contest/weekly-contest-185/display-table-of-food-orders-in-a-restaurant/solution_test.go, contest/weekly-contest-185/reformat-the-string/solution.go, contest/weekly-contest-185/reformat-the-string/solution_test.go
- Reformat The String: greedy
- Display Table of Food Orders in a Restaurant: using slice, hashmap and sort
=> Weekly contest 185

explore/other/card/30-day-leetcoding-challenge/528/week-4/bitwiseandofnumbersrange/solution.go, explore/other/card/30-day-leetcoding-challenge/528/week-4/bitwiseandofnumbersrange/solution_test.go
SeeAlso:
- https://leetcode.com/problems/bitwise-and-of-numbers-range/discuss/56719/JavaPython-easy-solution-with-explanation
=> Bitwise AND of Numbers Range: using bitwise

explore/other/card/30-day-leetcoding-challenge/528/week-4/lrucache/solution.go, explore/other/card/30-day-leetcoding-challenge/528/week-4/lrucache/solution_test.go
See: https://leetcode.com/problems/lru-cache/discuss/111256/Golang-solution-using-Doubly-liked-list-and-hash-map
=> LRU Cache: Doubly-linked list and hash map

contest/biweekly-contest-25/kidswiththegreatestnumberofcandies/solution.go, contest/biweekly-contest-25/kidswiththegreatestnumberofcandies/solution_test.go, contest/biweekly-contest-25/maxdifferenceyoucangetfromchanginganinteger/solution.go, contest/biweekly-contest-25/maxdifferenceyoucangetfromchanginganinteger/solution_test.go
- Kids With the Greatest Number of Candies: 2 liners simple solution
Max Difference You Can Get From Changing an Integer: brute force solution
=> Biweekly contest 25

contest/weekly-contest-187/checkifall1sareatleastlengthkplacesaway/solution.go, contest/weekly-contest-187/checkifall1sareatleastlengthkplacesaway/solution_test.go, contest/weekly-contest-187/destinationcity/solution.go, contest/weekly-contest-187/destinationcity/solution_test.go, contest/weekly-contest-187/ongestcontinuoussubarraywithabsolutedifflessthanorequaltolimit/solution.go, contest/weekly-contest-187/ongestcontinuoussubarraywithabsolutedifflessthanorequaltolimit/solution_test.go
- Destination City: using hashmap
- Check If All 1's Are at Least Length K Places Away: using pointer and flag
- Longest Continuous Subarray With Absolute Diff Less Than or Equal to Limit: greedy
=> Weekly contest 187

explore/other/card/may-leetcoding-challenge/week-1/firstuniquecharacterinastring/solution.go, explore/other/card/may-leetcoding-challenge/week-1/firstuniquecharacterinastring/solution_test.go
- Best solution: using []byte and slice https://github.com/lupinthe14th/leetcode/pull/163/commits/51207db684b683e72274c13ee6e67005f38139b6
=> First unique characterina string

explore/other/card/may-leetcoding-challenge/week-2/singleelementinasortedarray/solution.go, explore/other/card/may-leetcoding-challenge/week-2/singleelementinasortedarray/solution_test.go
The intuition was good, but we couldn't implement it.
=> Single elementina sorted array

contest/weekly-contest-182/count-number-of-teams/solution.go, contest/weekly-contest-182/count-number-of-teams/solution_test.go, contest/weekly-contest-182/design-underground-system/solution.go, contest/weekly-contest-182/design-underground-system/solution_test.go, contest/weekly-contest-182/find-lucky-integer-in-an-array/solution.go, contest/weekly-contest-182/find-lucky-integer-in-an-array/solution_test.go
- Find Lucky Integer in an Array: hashmap
=> weekly-contest-182

explore/other/card/may-leetcoding-challenge/week-2/removekdigits/solution.go, explore/other/card/may-leetcoding-challenge/week-2/removekdigits/solution_test.go
=> Remove k digits

explore/other/card/may-leetcoding-challenge/week-4/constructbinarysearchtreefrompreordertraversal/solution.go, explore/other/card/may-leetcoding-challenge/week-4/constructbinarysearchtreefrompreordertraversal/solution_test.go
https://leetcode.com/explore/challenge/card/may-leetcoding-challenge/537/week-4-may-22nd-may-28th/3339/discuss/252232/JavaC++Python-O(N)-Solution
=> Construct Binary Search Tree from Preorder Traversal: seen solution

explore/other/card/may-leetcoding-challenge/week-4/uncrossedlines/solution.go, explore/other/card/may-leetcoding-challenge/week-4/uncrossedlines/solution_test.go
seen: https://leetcode.com/problems/uncrossed-lines/discuss/282842/JavaC++Python-DP-The-Longest-Common-Subsequence
=> Uncrossed Lines: DP, The Longest Common Subsequence

explore/other/card/may-leetcoding-challenge/week-4/contiguousarray/solution.go, explore/other/card/may-leetcoding-challenge/week-4/contiguousarray/solution_test.go
=> Contiguous Array: seen text solution

explore/other/card/june-leetcoding-challenge/week-1/coinchange2/solution.go, explore/other/card/june-leetcoding-challenge/week-1/coinchange2/solution_test.go
=> Coin Change 2: dp solution

explore/other/card/june-leetcoding-challenge/week-2/searchinsertposition/solution.go, explore/other/card/june-leetcoding-challenge/week-2/searchinsertposition/solution_test.go
liner search solution: self solved
binary search solution: seen discuss
=> Search insert position

explore/other/card/june-leetcoding-challenge/week-3/dungeongame/solution.go, explore/other/card/june-leetcoding-challenge/week-3/dungeongame/solution_test.go
=> Dungeon Game: dp solution

explore/other/card/june-leetcoding-challenge/week-4/singlenumberii/solution.go, explore/other/card/june-leetcoding-challenge/week-4/singlenumberii/solution_test.go
=> Single Number II: bitwise solution

explore/other/card/june-leetcoding-challenge/week-5/uniquepaths/solution.go, explore/other/card/june-leetcoding-challenge/week-5/uniquepaths/solution_test.go
=> Unique Paths: seen discuss

explore/other/card/june-leetcoding-challenge/week-5/wordsearchii/solution.go, explore/other/card/june-leetcoding-challenge/week-5/wordsearchii/solution_test.go
=> Word Search II: seen discuss

explore/other/card/july-leetcoding-challenge/week-1/prisoncellsafterndays/solution.go, explore/other/card/july-leetcoding-challenge/week-1/prisoncellsafterndays/solution_test.go
愚直なTLE実装後、ヒントをみてループになったらどうにかするんだろうと直感したが、実装できなかった。
=> Prison Cells After N Days: seen discuss

explore/learn/card/data-structure-tree/traverse-a-tree/binarytreepreordertraversal/solution.go, explore/learn/card/data-structure-tree/traverse-a-tree/binarytreepreordertraversal/solution_test.go
Pre-order traversal is to visit the root first. Then traverse the left subtree. Finally, traverse the right subtree.
=> Binary Tree Preorder Traversal: recursive solution

explore/learn/card/data-structure-tree/traverse-a-tree/binarytreepreordertraversal/solution_test.go
=> Binary Tree Preorder Traversal: refactor code

explore/learn/card/data-structure-tree/traverse-a-tree/binarytreeinordertraversal/solution.go, explore/learn/card/data-structure-tree/traverse-a-tree/binarytreeinordertraversal/solution_test.go
In-order traversal is to traverse the left subtree first. Then visit the root. Finally, traverse the right subtree.
=> Binary Tree Inorder Traversal: recursive solution

explore/other/card/july-leetcoding-challenge/week-1/islandperimeter/solution.go, explore/other/card/july-leetcoding-challenge/week-1/islandperimeter/solution_test.go
1. 島なら基本+4
1. 上下左右が島ならそれぞれ-1
- ヘルパー関数を使う
- 戻り値となる値は共有する
- グリッドを一つずつ島かどうかチェック
- 島の場合、+4
- その後、上下左右をチェックするヘルパー関数を呼ぶ
- ヘルパー関数は枠外であればそのままリターン
- そうでなければその与えられた位置が島であれば-1
=> Island Perimeter: simple solution

explore/learn/card/data-structure-tree/traverse-a-tree/binarytreepostordertraversal/solution.go, explore/learn/card/data-structure-tree/traverse-a-tree/binarytreepostordertraversal/solution_test.go
Post-order traversal is to traverse the left subtree first. Then traverse the right subtree. Finally, visit the root.
=> Binary Tree Postorder Traversal: recursive solution

explore/other/card/july-leetcoding-challenge/week-2/flattenamultileveldoublylinkedlist/solution.go
1. rootから次のノードに一歩ずつ移動します
1. 子を持つノードの場合、その子供の最後まで移動して末尾のノードをその子供のノードの次のノードに接続します。
1. 子を持つノードに戻り、子を持つ次のノードが見つかるまで移動します。
1. nilになるまで繰り返します
=> Flatten a Multilevel Doubly Linked List: seen discuss

explore/other/card/july-leetcoding-challenge/week-2/reversebits/solution.go, explore/other/card/july-leetcoding-challenge/week-2/reversebits/solution_test.go
愚直。２進数文字列にしてからリバースして２進数文字列から10進数にパース
- bitsパッケージにそのまま解法をだせる関数があった
- Solutionにはいろいろな解法があったので写経
=> Reverse bits

explore/other/card/july-leetcoding-challenge/week-2/anglebetweenhandsofaclock/solution.go, explore/other/card/july-leetcoding-challenge/week-2/anglebetweenhandsofaclock/solution_test.go
- 短針が
- 1時間に移動する度数
- 1分間に移動する度数
- 長針が1分間に移動する度数
を求める。
- 短針は360を超えた場合は360を引いておく
- 長針引く短針の絶対値を求め、180を超えたら、360から引いた値、そうでなければその値が求める解
=> Angle Between Hands of a Clock: arthmetic solution

contest/weekly-contest-197/numberofgoodpairs/[, contest/weekly-contest-197/numberofgoodpairs/solution.go, contest/weekly-contest-197/numberofgoodpairs/solution_test.go, contest/weekly-contest-197/numberofsubstringswithonly1s/solution.go, contest/weekly-contest-197/numberofsubstringswithonly1s/solution_test.go, contest/weekly-contest-197/pathwithmaximumprobability/solution.go, contest/weekly-contest-197/pathwithmaximumprobability/solution_test.go
Path with Maximum Probability:
Bellman Ford Algorithm 重み付き有向グラフにおいてある単一始点からの最短経路を見つけるアルゴリズムで、正の辺と負の辺を持つことができます。
=> Weekly contest 197

explore/other/card/july-leetcoding-challenge/week-3/reversewordsinastring/solution.go, explore/other/card/july-leetcoding-challenge/week-3/reversewordsinastring/solution_test.go
=> Reverse Words in a String: simple solution

explore/other/card/july-leetcoding-challenge/week-3/mypow/solution.go, explore/other/card/july-leetcoding-challenge/week-3/mypow/solution_test.go
nが負の場合で結果の処理を分ける
xのn乗はbitを使うと速そうだけど、float64でできるのかよくわからない・・・
ってことで、Discuss参照。
=> Pow(x, n): math, bitwise solution

explore/other/card/july-leetcoding-challenge/week-3/topkfrequentelements/solution.go, explore/other/card/july-leetcoding-challenge/week-3/topkfrequentelements/solution_test.go
- ハッシュマップにその数字の出現回数を記録
- 出現回数をインデックスにして、その数字をスライスに格納
- 出現回数が多い順に解答用のスライスに格納してスライスのサイズがkを超えたらブレイク
=> Top k frequent elements

explore/other/card/july-leetcoding-challenge/week-3/coursescheduleii/solution.go, explore/other/card/july-leetcoding-challenge/week-3/coursescheduleii/solution_test.go
using Node Indegree via BFS
グラフ問題。解法は思い付かず。
ヒントを見てトポロジカルソートだとわかり、参考書見たりして解いたが、WA
対応がわからず、Solution確認
実装も少々手間取る。
類題を解く必要がありますね
=> Course Schedule II: seen solution

contest/weekly-contest-198/numberofnodesinthesub-treewiththesamelabel/solution.go, contest/weekly-contest-198/numberofnodesinthesub-treewiththesamelabel/solution_test.go, contest/weekly-contest-198/waterbottles/solution.go, contest/weekly-contest-198/waterbottles/solution_test.go
飲んだボトルの数と空のボトルを管理してループ。空のボトルが交換可能なボトルの個数を下回ったらブレイク
時間がかかりすぎてテンパった。落ち着いて動作を一つずつ実装してAC
グラフ作って子ノードがあればその子ノードで親ノードと同じアルファベットなら解答リストのノード番号のインデックスをインクリメント。だが結局考えが足りず及ばずDiscuss参照
- 無向グラフなのでAdjListを作る時にsrcとdistを逆にしたのも作る必要があった
- 最初、bfsで作ったが、dfsのが子ノード以下でのアルファベットに対したリストを保持する必要があるので自然
=> Weekly contest 198

explore/other/card/july-leetcoding-challenge/week-3/addbinary/solution.go, explore/other/card/july-leetcoding-challenge/week-3/addbinary/solution_test.go
- 制約で桁数が大きいので数字に変換して和を行ってからビットに戻す方式は取れない
- byteにして値をパターン毎に対処すれば良さそう
- 桁数があってないのが面倒なので桁数をそろえる
- 桁数そろえるや、比較する際に逆にしてからやった方が楽だと思ったが、そのままにして比較するポインターを右から読んでいけばシンプルなことに気がつく
- 最後にフラグが立っている場合は一番左に1を追加する
- 桁数をそろえるアルゴリズムがバグ出しまくってた 😢
=> Add Binary: simple solution

explore/other/card/july-leetcoding-challenge/week-3/removelinkedlistelements/solution.go, explore/other/card/july-leetcoding-challenge/week-3/removelinkedlistelements/solution_test.go
空のListNodeを作って値を入れていく。。。が、うまくできず。
解決もできず、今まで解いた類似ソース b704f8dedb76e821218e41d6c8e3b6877d2bff65 を見てAC
=> Remove Linked List Elements: seen past solved solution

explore/learn/card/data-structure-tree/conclusion/serializeanddeserializebinarytree/solution.go, explore/learn/card/data-structure-tree/conclusion/serializeanddeserializebinarytree/solution_test.go
SeeAlso: https://leetcode.com/explore/learn/card/data-structure-tree/133/conclusion/995/discuss/688621/Go-bfs
さっぱりわからず。Codec構造体をどう作るんだろうと思ってた。
Discuss参照。
- Codec構造体は空
- コンストラクタも空のCodec構造体を返す
- RecursiveとDFSのSolutionがあったけど、最近慣れたきたBFSパターンを採択
- キューに突っ込んで、その長さ分ループを回すやり方は初めて見た
- ポインタを使った関数を無名関数にして実装したが、後でリファクタリングした
=> Serialize and Deserialize Binary Tree: seen discuss

explore/learn/card/fun-with-arrays/introduction/maxconsecutiveones/solution.go, explore/learn/card/fun-with-arrays/introduction/maxconsecutiveones/solution_test.go
- 1が続けばカウンターをインクリメント。0が来たらカウンターを初期化
- ループの都度、カウンターと、過去の最大値を比較して大きくなっていたら更新
- 最終的に得られた最大値が求める値
=> Max Consecutive Ones: simple solution

explore/other/card/july-leetcoding-challenge/week-3/wordsearch/solution.go, explore/other/card/july-leetcoding-challenge/week-3/wordsearch/solution_test.go
- Trie使えばいいと思ってた。が、TLE
- Hash map使って、探索開始点だけ調べてからDFSして、全探索。これもTLE
- 1つでも成功したら抜けるGreedyで行けばTLEならないのではと試行錯誤したけど、実装迷子になったのでDiscuss参照
- 迷子中に書いてた実装と似ていたが要所要所間違ってた
=> Word search

explore/other/card/july-leetcoding-challenge/week-4/binarytreezigzaglevelordertraversal/[, explore/other/card/july-leetcoding-challenge/week-4/binarytreezigzaglevelordertraversal/solution.go, explore/other/card/july-leetcoding-challenge/week-4/binarytreezigzaglevelordertraversal/solution_test.go
- レベルも引数に渡して再帰
- 奇数か偶数かで振る舞い変えればいけるはず
いけたんだけど、使い方がいろいろ誤っててWA
結局また実装迷子になりDiscuss参照してAC
=> Binary Tree Zigzag Level Order Traversal: seen in the discuss

explore/learn/card/fun-with-arrays/introduction/findnumberswithevennumberofdigits/solution.go, explore/learn/card/fun-with-arrays/introduction/findnumberswithevennumberofdigits/solution_test.go
intの桁数計算は10で割れる数を数える。後は、その数をand 1 して0な数を数える
=> Find Numbers with Even Number of Digits: simple solution

explore/learn/card/fun-with-arrays/introduction/squaresofasortedarray/solution.go, explore/learn/card/fun-with-arrays/introduction/squaresofasortedarray/solution_test.go
「インプレースで2乗してソート」すれば良いんだろうけど、もっと効率のいい解ありそうだな・・・
一旦インプレースで2乗してソートの解法でポスト。速い解法見たら納得のアルゴリズム。
もともと与えられた数列は、ソートされているので、左端と右端から初めて2乗して大きい方を別に用意した元の数列の右からセットしていけば良い。セットした方を右端なら右端用のポインターをデクリメント。左端なら左端用のポインターをインクリメント
=> Squaresofa sorted array

explore/other/card/july-leetcoding-challenge/week-4/singlenumberiii/solution.go, explore/other/card/july-leetcoding-challenge/week-4/singlenumberiii/solution_test.go
過去似たようなのやったけど覚えてない 😢 
とりあえず、求めている解法ではないけどhash map使ってAC
XORを使います。2回のパスで実行します。
Pass 1: 最初のパスでは、配列のすべての要素をXORし、求めるべき2つの数値のXORを求めます。2つの数値は区別されているのでXORの結果にはセットビット（つまり値1）が存在しなければならないことに注意します。
探索を任意のセットビットを取り出します。
Pass 2: 次のパスでは全ての数字を２つのグループに分けます、1つは前述のビットがセットされているもの、もう一つは前述のビットがセットされていないものです。
見つける必要のある２つの異なる数字は、２つのグループに分類されなければなりません。
=> Single number iii

explore/learn/card/fun-with-arrays/inserting-items-into-an-array/duplicatezeros/solution.go, explore/learn/card/fun-with-arrays/inserting-items-into-an-array/duplicatezeros/solution_test.go
=> Duplicate Zeros: seen solution

explore/other/card/july-leetcoding-challenge/week-4/findminimuminrotatedsortedarrayii/solution.go, explore/other/card/july-leetcoding-challenge/week-4/findminimuminrotatedsortedarrayii/solution_test.go
さっぱりわからん 😭 
Cracking the coding interview を見たら似たような問題があり、ヒント参照すると、Binary Search approachが示唆されていた。
しかし、中身のロジックを実装できずDiscuss参照。
=> Find Minimum in Rotated Sorted Array II: using binary search solution

explore/other/card/july-leetcoding-challenge/week-4/adddigits/solution.go, explore/other/card/july-leetcoding-challenge/week-4/adddigits/solution_test.go
- ループすればすぐ出来るけどO(1)の解なので数学的考察なんだろなと
- わからずヒントをみると列挙してみて、周期的な振る舞いになっていないかなどのヒントが
- 9で割った余りが解っぽい
- 単純に9で割った余りだと、9の場合WA, 0の場合WA
- 最初は9以下と割った余りが0とそれ以外のそれぞれの解を返す
- 9以下はそのままの値を返す
- 9で割って余りが0の場合は9を返す
- それ以外は9で割った余りを返す。
=> Add digits

explore/other/card/july-leetcoding-challenge/week-4/allpathsfromsourcetotarget/[, explore/other/card/july-leetcoding-challenge/week-4/allpathsfromsourcetotarget/solution.go, explore/other/card/july-leetcoding-challenge/week-4/allpathsfromsourcetotarget/solution_test.go
DFSで全探索
WAとなる。順番が意図したものになってないな原因がわからず。
DFSの実装がいけてないのかと思い、自己解決は諦めDiscussion参照した（Java, C++）が実装は悪くなさそう。
Goの実装を参照したところ、スライスを新しく作ってコピーしていた。
その実装を真似たところAC。
スライスのポインターが切れないGoの独特のものが原因でWAとなっていた。
=> All Paths From Source to Target: using dfs solution

explore/other/card/july-leetcoding-challenge/week-4/constructbinarytreefrominorderandpostordertraversal/solution.go, explore/other/card/july-leetcoding-challenge/week-4/constructbinarytreefrominorderandpostordertraversal/solution_test.go
- あー、前にTree Learnでやってさっぱりわからなかったやつだ
- 今回もわからず写経
- 再度復習する必要ありますね
=> Construct Binary Tree from Inorder and Postorder Traversal: sutra

explore/other/card/july-leetcoding-challenge/week-5/besttimetobuyandsellstockwithcooldown/[, explore/other/card/july-leetcoding-challenge/week-5/besttimetobuyandsellstockwithcooldown/solution.go, explore/other/card/july-leetcoding-challenge/week-5/besttimetobuyandsellstockwithcooldown/solution_test.go
愚直に値上がりしたら売って休んで買って売って休んでの繰り返し
と、思ったがWA。
これ以上、思い付かずDiscuss参照
- DPなのねこれ。ヒント見てもわからないのでDisscuss参照したけどそれでもわからない
=> Best timeto buyand sell stockwith cooldown

explore/other/card/july-leetcoding-challenge/week-5/wordbreakii/solution.go, explore/other/card/july-leetcoding-challenge/week-5/wordbreakii/solution_test.go, go.mod, go.sum
全くわからん。sの間にスペースを入れて総当たりだと間に合わないのではないか。で、Discuss参照
- メモ化DPとHashmapが有効なようだ。
`Using DFS directly will lead to TLE, so I just used HashMap to save the previous results to prune duplicated branches, as the following:`
[See](https://leetcode.com/problems/word-break-ii/discuss/44167/My-concise-JAVA-solution-based-on-memorized-DFS)
- このJavaの実装をGoに焼き直ししようとしたが、Linkd Listの扱いに困ったので、Goの[実装例](https://leetcode.com/problems/word-break-ii/discuss/596188/DP-solution)を写経することにした。
=> Word break ii

explore/other/card/august-leetcoding-challenge/week-1/detectcapital/solution.go, explore/other/card/august-leetcoding-challenge/week-1/detectcapital/solution_test.go
- 例示されたケースを愚直に実装
- isUpperとisLowerも実装（stringsパッケージ にはなさそうだった）
=> Detect Capital: simple solution

explore/other/card/august-leetcoding-challenge/week-1/validpalindrome/solution.go, explore/other/card/august-leetcoding-challenge/week-1/validpalindrome/solution_test.go
英数字のみbyteスライスに入れて前と後からgreedyに比較。全部すり抜けたら True
条件誤って、数字を除外していたため3WA
=> Valid palindrome

explore/other/card/august-leetcoding-challenge/week-1/poweroffour/solution.go, explore/other/card/august-leetcoding-challenge/week-1/poweroffour/solution_test.go
=> Power of Four: seen discuss

explore/other/card/august-leetcoding-challenge/week-1/addandsearchworddatastructuredesign/solution.go, explore/other/card/august-leetcoding-challenge/week-1/addandsearchworddatastructuredesign/solution_test.go
- trie node使うのかな・・・。でもどう実装して良いかよー分からん。
- Discus 参照。Trie node使ってる解法がMost Votesだった。
- backtracking and trie
=> Add and Search Word - Data structure design: seen discuss, using trie node solution

explore/other/card/august-leetcoding-challenge/week-1/findallduplicatesinanarray/solution.go, explore/other/card/august-leetcoding-challenge/week-1/findallduplicatesinanarray/solution_test.go
- sortして前のと比較すれば良いのでは
- sortしたらO(n) time じゃなくて、O(nlogn) time なので制約違反ですね。
- Discuss参照したけど、ほんとどうしたらこういう解法が出てくるのか
=> Find all duplicatesinan array

explore/other/card/august-leetcoding-challenge/week-3/distributecandiestopeople/solution.go, explore/other/card/august-leetcoding-challenge/week-3/distributecandiestopeople/solution_test.go
2重ループで間に合うので素直に実装
Discus見たらもっとシンプルな実装があったのでそちらでも実装。パフォーマンスは変わらない
=> Distribute candiesto people

explore/other/card/august-leetcoding-challenge/week-3/numberswithsameconsecutivedifferences/solution.go, explore/other/card/august-leetcoding-challenge/week-3/numberswithsameconsecutivedifferences/solution_test.go
- 桁の頭となる数字から次の桁の数字を決めて配列に格納しての再帰
- 終了条件は格納する配列の桁数が与えられた条件になったら
- 例外は次の数が0より小さい場合と9より大きい場合
=> Numbers with same consecutive differences

explore/other/card/august-leetcoding-challenge/week-3/reorderlist/solution.go, explore/other/card/august-leetcoding-challenge/week-3/reorderlist/solution_test.go
一旦全部の値をスライスに格納して、リオーダーしてからheadに戻す
上記考えはいけてない
- slow, fastの考え方と、prevを使う
- よーわからん 😢 
https://leetcode.com/problems/reorder-list/discuss/577883/Go-Solution
=> Reorder List: seen discuss

explore/other/card/august-leetcoding-challenge/week-4/sumofleftleaves/solution.go, explore/other/card/august-leetcoding-challenge/week-4/sumofleftleaves/solution_test.go
- いつもの再帰で巡回
- 左からきたフラグを持たせる
- 末端であることと左からきたことがわかれば値を足す
- 最初は全ての左の値を足すのだと思って1WA
=> Sum of Left Leaves: using recursive solution, postorder traversal

explore/other/card/august-leetcoding-challenge/week-4/minimumcostfortickets/solution.go, explore/other/card/august-leetcoding-challenge/week-4/minimumcostfortickets/solution_test.go
- DFSだと思った
- DFSな解はOOMとなった
- 解法の方針が間違っていそう
- 既に3 interval使っていたので諦めてSolutionへ
- dpな解法でした
- それぞれの日について、もし今日旅行する必要がないならチケットを購入しないで待つのが良策。
- 今日旅行しなければいけない場合、3つの選択肢から一つ選ばなければならない。 
- この選択肢を再帰で表現して動的計画法を使う。
- dp(i) がi日目から旅行計画を実行するコストであるとする
- dp(i)=min(dp(i+1)+costs[0],dp(i+7)+costs[1],dp(i+30)+costs[2])
=> Minimum Cost For Tickets: using dp solution

explore/other/card/august-leetcoding-challenge/week-3/sortarraybyparity/solution.go, explore/other/card/august-leetcoding-challenge/week-3/sortarraybyparity/solution_test.go
appendだと遅いので、インデックス指定して書いていった。
32ms -> 12ms
8.9 MB -> 5 MB
=> Sort Array By Parity: refactor code

explore/other/card/august-leetcoding-challenge/week-4/fizzbuzz/solution.go, explore/other/card/august-leetcoding-challenge/week-4/fizzbuzz/solution_test.go
- 典型で解く
- ifだと見通しが悪くなるのでswitchを利用
=> Fizz Buzz: simple solution

explore/other/card/august-leetcoding-challenge/week-4/findrightinterval/solution.go, explore/other/card/august-leetcoding-challenge/week-4/findrightinterval/solution_test.go
- hash map使って近いところから検索していく
- 問題を理解するのにものすごく時間がかかった
=> Find Right Interval: using map solution

explore/other/card/august-leetcoding-challenge/week-4/implementrand10usingrand7/solution.go
=> Implement Rand10() Using Rand7(): using Utilizing out-of-range samples

explore/other/card/august-leetcoding-challenge/week-4/implementrand10usingrand7/solution.go, explore/other/card/august-leetcoding-challenge/week-5/largestcomponentsizebycommonfactor/solution.go, explore/other/card/august-leetcoding-challenge/week-5/largestcomponentsizebycommonfactor/solution_test.go
- さっぱりわからない
- そもそもExample 3の構造体になるのがよーわからん
- discuss 参照
- Union-find tree構造とのこと
- abc177/dもそれで解けるとかで解説みたけどさっぱり
- 写経でAC
- もっと速い解き方があるようだ
=> Largest Component Size by Common Factor: seen discuss

explore/other/card/august-leetcoding-challenge/week-5/deletenodeinabst/solution.go, explore/other/card/august-leetcoding-challenge/week-5/deletenodeinabst/solution_test.go
- いつもの再帰でやろう
- あれ？keyと一致したValを消す場合、その下にぶら下がっている辺があった場合の振る舞いをどうすれば良いかわからない
- 思慮したけど見当つかないのでdiscuss参照して写経
=> Delete Node in a BST: seen disucuss

.github/labeler.yml, explore/other/card/september-leetcoding-challenge/README.md, explore/other/card/september-leetcoding-challenge/week-1/repeatedsubstringpattern/solution.go, explore/other/card/september-leetcoding-challenge/week-1/repeatedsubstringpattern/solution_test.go
=> Repeated substring pattern

explore/other/card/september-leetcoding-challenge/week-1/partitionlabels/solution.go, explore/other/card/september-leetcoding-challenge/week-1/partitionlabels/solution_test.go
さっぱりわからん
- Solutionをみた
- Intuition読んだけどそれでもわからん
- 9月はこんなのばっかり
=> Partition Labels: seen solution

explore/other/card/september-leetcoding-challenge/week-1/allelementsintwobinarysearchtrees/solution.go, explore/other/card/september-leetcoding-challenge/week-1/allelementsintwobinarysearchtrees/solution_test.go
- スライスにValすべて突っ込んでソートした結果を返す。
time: O(nlogn)
space: O(n)
ソートしているから上記だと思ったんだけど、Discuss見ると、time&Space O(n)になってるな
=> All Elements in Two Binary Search Trees: using preorder traversal

explore/other/card/september-leetcoding-challenge/week-1/imageoverlap/solution.go, explore/other/card/september-leetcoding-challenge/week-1/imageoverlap/solution_test.go
- 片方をずらして1であるかつAとBの値が一緒の数の最大値を求める
- プラス方向にのみずらしていたので、マイナス方向にすらしたのがなくて1WA
=> Image Overlap: bruteforce solution

explore/other/card/september-leetcoding-challenge/week-1/wordpattern/solution.go, explore/other/card/september-leetcoding-challenge/week-1/wordpattern/solution_test.go
- patternの文字をマップキーにして、対する文字列strを空白でsplitしたスライスを格納していく
- 既にそのキーに値が入っていたら対するスライスの文字列と一致しない場合はFalse
- すべて抜けた場合、別のキーで同じ文字列が格納されていないかをチェックする
- 英子文字なので26こ程度なのでBruteforceで調べた
AC後に提出したのより速いコードを見たら別のキーで同じ文字列が入っていないかを調べるのはBruteforceじゃない良いやり方があった
=> Word Pattern: using map

explore/other/card/september-leetcoding-challenge/week-2/sumofroottoleafbinarynumbers/solution.go, explore/other/card/september-leetcoding-challenge/week-2/sumofroottoleafbinarynumbers/solution_test.go
- preorder traversalして、値を左シフトしていく
- ノードの左右がnulになったら足す
=> Sumof root to leaf binary numbers

explore/other/card/september-leetcoding-challenge/week-2/compareversionnumbers/solution.go, explore/other/card/september-leetcoding-challenge/week-2/compareversionnumbers/solution_test.go
- using greedy
- . でsplitして、スライスの最大長分ループで回す
- スライス長を超過した場合は、デフォルトの0で考える
- 文字列を数値にコンバートして差が出たらそこで与えられた判定値の1か-1を返して終わり
- すべての判定がスルーされたら0を返して終わり
=> Compare Version Numbers: using simple solution

explore/other/card/september-leetcoding-challenge/week-2/bullsandcows/solution.go, explore/other/card/september-leetcoding-challenge/week-2/bullsandcows/solution_test.go
スライディングウインドウでやればできるかな？
cowの値の出し方がよーわからず。このゲームの仕様を理解していないからか。4WA出してギブアップ。
😿
=> Bulls and Cows: seen disucuss

explore/other/card/september-leetcoding-challenge/week-2/maximumproductsubarray/solution.go, explore/other/card/september-leetcoding-challenge/week-2/maximumproductsubarray/solution_test.go
- greedy
o(n^2)の解法なので遅い（100ms）。discuss見たらO(n)の解法があって写経。submitしたら0msでした。
=> Maximum product subarray

explore/other/card/september-leetcoding-challenge/week-2/combinationsumiii/solution.go, explore/other/card/september-leetcoding-challenge/week-2/combinationsumiii/solution_test.go
- recursiveな解決だろうなと
- 重複なしのcombinationの作り方が苦手
- 苦手意識が払拭できずsolution確認
- Linkedlistな構造体を使うjavaの解法見て、翻訳するのつらいのでgoの実装を参考に写経
=> Combination Sum III: seen solution and discuss

explore/other/card/september-leetcoding-challenge/week-2/insertinterval/solution.go, explore/other/card/september-leetcoding-challenge/week-2/insertinterval/solution_test.go
- starlight forwardかな・・・
- 思った実装でサンプル通過したけどsubmitしたらWAで直してsubmitを3回繰り返す
- 時間切れなのでDiscuss参照したらJavaでは同じ感じで実装している方がいたが・・・goに翻訳するの辛そうなのでgo 実装を参照して写経
=> Insert Interval: seen discuss go implementation

explore/other/card/september-leetcoding-challenge/week-2/houserobber/solution.go, explore/other/card/september-leetcoding-challenge/week-2/houserobber/solution_test.go
愚直
- 愚直にやってWA連発
- discuss見たら典型DP（topdown dp）
- この解法に脊髄反射でいけなかったのが😭
=> House Robber: timeover, seen discus; using topdown dp

explore/other/card/september-leetcoding-challenge/week-3/lengthoflastword/solution.go, explore/other/card/september-leetcoding-challenge/week-3/lengthoflastword/solution_test.go
- 愚直に空白でスライスに分けて最後のスライスの長さを返す
- 最後に空白がある場合の考慮もれで1WA 😿
=> Length of Last Word: using strings package

explore/other/card/september-leetcoding-challenge/week-3/robotboundedincircle/solution.go, explore/other/card/september-leetcoding-challenge/week-3/robotboundedincircle/solution_test.go
dfs?bfs?
- Hintを読むとdfsとかbfsとかそんなこと考えなくても良いことがわかる
- 愚直に実装してSubmitしたらWA
- なんだかわからず見直ししてもわからず
- 降参してDiscuss見たら同じ考えで実装している例がすぐ見つかる
- よくよく見ると、北から西に向ける時の数値を間違えていることがわかる
- 単なるバグでした
=> Robot Bounded In Circle: seen hint and discuss

explore/other/card/september-leetcoding-challenge/week-3/maximumxoroftwonumbersinanarray/solution.go, explore/other/card/september-leetcoding-challenge/week-3/maximumxoroftwonumbersinanarray/solution_test.go
とりあえず総当たり: https://github.com/lupinthe14th/leetcode/commit/da2ba92be774988113f2f6999acee8c03a19fbce
- 総当たりでも1WA
- O(n)の解放考えたけど思いつかないのでDiscuss参照
- Trie Tree Solution: https://github.com/lupinthe14th/leetcode/commit/551151ef7cbe2bd6f09aa91365467a842c7c7d4a
=> Maximum xo rof two numbersinan array

explore/other/card/september-leetcoding-challenge/week-4/majorityelementii/solution.go, explore/other/card/september-leetcoding-challenge/week-4/majorityelementii/solution_test.go
さっぱりわからん
- Solution見ても理解できない
- とりあえず写経
=> Majority Element II: seen solution

explore/other/card/september-leetcoding-challenge/week-4/gasstation/solution.go, explore/other/card/september-leetcoding-challenge/week-4/gasstation/solution_test.go
dfsでいける
- 書いててよーわからんdfsになった
- それでも一発AC
- でも遅い
- 速い解法見てわかりやすいのがあったので[それ](https://github.com/lupinthe14th/leetcode/commit/3d8ca413bc73d2201ab1323a25ff0b1c56361211)は写経
=> Gas station

explore/other/card/september-leetcoding-challenge/week-5/WordBreak/solution.go, explore/other/card/september-leetcoding-challenge/week-5/WordBreak/solution_test.go
- stringsパッケージ使って愚直でやるのかと思ったが、うまくstringsパッケージ使いきれず
- 時間も1ポモドーロ使ったのでdiscuss参照
dpか...。まだ直感が良くない。
=> Word Break: seen discuss

.github/labeler.yml, explore/other/card/october-leetcoding-challenge/week-1/combinationsum/solution.go, explore/other/card/october-leetcoding-challenge/week-1/combinationsum/solution_test.go
- dfs?
- 時間取れなくて時間ぎれ
- ゆっくり考える余裕もないので写経することに
- backtrackだった
=> Combination Sum: seen discuss

explore/other/card/october-leetcoding-challenge/week-1/removecoveredintervals/solution.go, explore/other/card/october-leetcoding-challenge/week-1/removecoveredintervals/solution_test.go
1ポモドーロではわからず、Discuss参照
sort & greedy
- 2019年12月に解いてた。なんとなく見覚えがあるなと思ったが忘れていた
=> Remove Covered Intervals: seen discuss

explore/other/card/october-leetcoding-challenge/week-1/rotatelist/solution.go, explore/other/card/october-leetcoding-challenge/week-1/rotatelist/solution_test.go
長さ求めて、実際に回す数計算してその端数を回すのかな・・・。
実装が思いつかずDiscuss参照。
=> Rotate List: seen discuss

explore/other/card/october-leetcoding-challenge/week-2/sortlist/solution.go, explore/other/card/october-leetcoding-challenge/week-2/sortlist/solution_test.go
Followupは諦めた。sortパッケージを利用。
marge sort の実装か。
=> Sort List: using sort & other space

explore/other/card/october-leetcoding-challenge/week-2/houserobberii/solution.go, explore/other/card/october-leetcoding-challenge/week-2/houserobberii/solution_test.go
greedy
hintみて解いたけど、考慮漏れ。で、Discuss参照。DPか。。。
=> House Robber II: seen discuss

explore/other/card/october-leetcoding-challenge/week-3/rotatearray/solution.go, explore/other/card/october-leetcoding-challenge/week-3/rotatearray/solution_test.go
=> Rotate Array: using extra array

explore/other/card/october-leetcoding-challenge/week-3/asteroidcollision/solution.go, explore/other/card/october-leetcoding-challenge/week-3/asteroidcollision/solution_test.go
=> Asteroid Collision: seen discuss

explore/other/card/october-leetcoding-challenge/week-4/minimumdepthofbinarytree/solution.go, explore/other/card/october-leetcoding-challenge/week-4/minimumdepthofbinarytree/solution_test.go
traversalでいけるかな・・・。でいけず。何が何やらわからなくなり、Discuss参照
=> Minimum Depth of Binary Tree: seen discuss

explore/other/card/october-leetcoding-challenge/week-4/champagnetower/solution.go, explore/other/card/october-leetcoding-challenge/week-4/champagnetower/solution_test.go
=> Champagne Tower: seen discuss

explore/other/card/october-leetcoding-challenge/week-3/summaryranges/solution.go, explore/other/card/october-leetcoding-challenge/week-3/summaryranges/solution_test.go
=> Summary Ranges: greedy?

explore/other/card/november-leetcoding-challenge/week-1/consecutivecharacters/solution.go, explore/other/card/november-leetcoding-challenge/week-1/consecutivecharacters/solution_test.go
=> Consecutive Characters: simple solution

explore/other/card/november-leetcoding-challenge/week-1/minimumcosttomovechipstothesameposition/solution.go, explore/other/card/november-leetcoding-challenge/week-1/minimumcosttomovechipstothesameposition/solution_test.go
1番多い数との差が奇数か偶数かを判定して・・。
で、解法がそれ以上思い付かずSolution見た
=> Minimum Cost to Move Chips to The Same Position: seen solution

explore/other/card/november-leetcoding-challenge/week-2/maximumdifferencebetweennodeandancestor/solution.go, explore/other/card/november-leetcoding-challenge/week-2/maximumdifferencebetweennodeandancestor/solution_test.go
=> Maximum Difference Between Node and Ancestor: seen solution

explore/other/card/november-leetcoding-challenge/week-2/flippinganimage/solution.go, explore/other/card/november-leetcoding-challenge/week-2/flippinganimage/solution_test.go
=> Flippingan image

explore/other/card/november-leetcoding-challenge/week-2/validsquare/solution.go, explore/other/card/november-leetcoding-challenge/week-2/validsquare/solution_test.go
雑念があって何も考えられず、写経。
Bruteforce approach
=> Valid Square: seen solution

explore/other/card/november-leetcoding-challenge/week-2/permutationsii/solution.go, explore/other/card/november-leetcoding-challenge/week-2/permutationsii/solution_test.go
Permutation苦手だなーで、Solution参照へ。
=> PermutationsII: seen solution

explore/other/card/november-leetcoding-challenge/week-3/rangesumofbst/solution.go, explore/other/card/november-leetcoding-challenge/week-3/rangesumofbst/solution_test.go
=> Range Sum of BST: using preorder traversal approach

explore/other/card/december-leetcoding-challenge/week-1/maximumdepthofbinarytree/solution.go, explore/other/card/december-leetcoding-challenge/week-1/maximumdepthofbinarytree/solution_test.go
=> Maximum Depth of Binary Tree: RP, repeat try

explore/other/card/december-leetcoding-challenge/week-1/linkedlistrandomnode/solution.go
list使えば良いかな。で、Follow upみて固まった。
=> Linked List Random Node: See solution: Approach 1: Fixed-Range Sampling

explore/other/card/december-leetcoding-challenge/week-1/increasingordersearchtree/solution.go, explore/other/card/december-leetcoding-challenge/week-1/increasingordersearchtree/solution_test.go
in-order traversal and array loop
=> Increasing Order Search Tree: seen discuss

explore/other/card/december-leetcoding-challenge/week-1/populatingnextrightpointersineachnodeii/solution.go, explore/other/card/december-leetcoding-challenge/week-1/populatingnextrightpointersineachnodeii/solution_test.go
=> Populating Next Right Pointers in Each Node II: saw past solution

explore/other/card/december-leetcoding-challenge/week-3/validatebinarysearchtree/solution.go, explore/other/card/december-leetcoding-challenge/week-3/validatebinarysearchtree/solution_test.go
- recursion ...
- I couldn't implementation
=> Validate Binary Search Tree: seen solution and discuss

explore/other/card/december-leetcoding-challenge/week-3/decodedstringatindex/solution.go, explore/other/card/december-leetcoding-challenge/week-3/decodedstringatindex/solution_test.go
=> Decoded stringat index

explore/other/card/december-leetcoding-challenge/week-4/balancedbinarytree/solution.go, explore/other/card/december-leetcoding-challenge/week-4/balancedbinarytree/solution_test.go
=> Balanced Binary Tree: seen solution

explore/other/card/december-leetcoding-challenge/week-4/nextgreaterelementiii/solution.go, explore/other/card/december-leetcoding-challenge/week-4/nextgreaterelementiii/solution_test.go
=> Next Greater Element III: seen discuss

.github/labeler.yml, explore/other/card/january-leetcoding-challenge-2021/week-1/mergetwosortedlists/solution.go, explore/other/card/january-leetcoding-challenge-2021/week-1/mergetwosortedlists/solution_test.go
=> Merge Two Sorted Lists: I looked at past solutions

explore/other/card/january-leetcoding-challenge-2021/week-1/removeduplicatesfromsortedlistii/solution.go, explore/other/card/january-leetcoding-challenge-2021/week-1/removeduplicatesfromsortedlistii/solution_test.go
- I thought 2 pointer approach, but couldn't implementation. 😭
=> Remove Duplicates from Sorted List II: seen discuss, recursive approach

explore/other/card/january-leetcoding-challenge-2021/week-1/kthmissingpositivenumber/solution.go, explore/other/card/january-leetcoding-challenge-2021/week-1/kthmissingpositivenumber/solution_test.go
=> Kth Missing Positive Number: simple solution

explore/other/card/january-leetcoding-challenge-2021/week-1/mergesortedarray/solution.go, explore/other/card/january-leetcoding-challenge-2021/week-1/mergesortedarray/solution_test.go
=> Merge Sorted Array: simple solution

explore/other/card/january-leetcoding-challenge-2021/week-1/addtwonumbers/solution.go, explore/other/card/january-leetcoding-challenge-2021/week-1/addtwonumbers/solution_test.go
=> Add two numbers

explore/other/card/january-leetcoding-challenge-2021/week-3/findthemostcompetitivesubsequence/solution.go, explore/other/card/january-leetcoding-challenge-2021/week-3/findthemostcompetitivesubsequence/solution_test.go
ref: https://leetcode.com/explore/challenge/card/january-leetcoding-challenge-2021/581/week-3-january-15th-january-21st/3611/discuss/952786/JavaC++Python-One-Pass-Stack-Solution
=> Find the Most Competitive Subsequence: seen discuss: use stack
